apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: azure-delete
  namespace: argo
spec:
  eventBusName: azure-delete
  template:
    serviceAccountName: argocd-workflow
  dependencies:
    - name: azure-delete
      eventSourceName: azure-delete
      eventName: azure-delete
  triggers:
    - template:
        name: azure-delete
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: azure-delete-
                labels:
                  app: azure-delete
              spec:
                entrypoint: remove-from-argocd
                serviceAccountName: argocd-workflow
                arguments:
                  parameters:
                  - name: cluster
                    # the value will get overridden by the event payload from azure-delete
                    value: ""
                templates:
                - name: remove-from-argocd
                  inputs:
                    parameters:
                    - name: cluster
                  container:
                    image: ghcr.io/eitco/eitco-builder:0.0.11
                    command: ["/bin/sh", "-c", "/etc/argocd-scripts/remove-from-argocd.sh {{inputs.parameters.cluster}}"]
                    volumeMounts:
                    - name: argocd-scripts
                      mountPath: /etc/argocd-scripts/
                    env:
                    - name: USERNAME
                      valueFrom:
                        secretKeyRef:
                          key: username
                          name: argocd-login
                    - name: PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: password
                          name: argocd-login
                  volumes:
                  - name: argocd-scripts
                    configMap:
                      name: azure-argocd-scripts
                      defaultMode: 0777
          parameters:
            - src:
                dependencyName: azure-delete
                dataKey: body.metadata.name
              dest: spec.arguments.parameters.0.value