---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-for-mgmt
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: 'git@github.com:eitco/argo-hub.git'
    targetRevision: main
    path: clusters/management-cluster/apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true