---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-workflows
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: 'git@github.com:eitco/argo-hub.git'
    targetRevision: 0.1.4
    path: clusters/management-cluster/argocd/cluster-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true