apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-projects-app.yaml
  - cluster-workflows-application.yaml
  - app-of-apps-for-mgmt.yaml
  - ./namespaces/
  - ./applicationsets/