apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policy-reporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/policy-reporter
    targetRevision: 2.21.4
    chart: policy-reporter
    helm:
      releaseName: policy-reporter
      values: |
        ui:
          enabled: true
        kyvernoPlugin:
          enabled: true
        ingress:
          enabled: false
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            cert-manager.io/cluster-issuer: smallstep-acme-http01
            traefik.ingress.kubernetes.io/router.tls: "true"
          className: "traefik"
          hosts:
            - host: kyverno-mgmt.projekte.eitco.de
          tls:
            - secretName: kyverno-policy-reporter-tls
              hosts:
                - kyverno-mgmt.projekte.eitco.de
  destination:
    name: in-cluster
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true