apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.1.1
    chart: kyverno
    helm:
      releaseName: kyverno
      values: |
        grafana:
          enabled: true
          labels:
            grafana_dashboards: "1"
          grafanaDashboard:
            create: false
            matchLabels:
              dashboards: "grafana"
  destination:
    name: in-cluster
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true