apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-default
  resources:
    requests:
      storage: 512Mi
