apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: 'git@github.com:eitco/argo-hub.git'
    path: clusters/management-cluster/apps/components/argocd-image-updater
    targetRevision: 0.1.4
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
