apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: default
  source:
    repoURL: 'git@github.com:eitco/argo-hub.git'
    path: clusters/management-cluster/apps/components/loki-stack
    targetRevision: 0.1.4
  destination:
    name: in-cluster
    namespace: loki-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true