apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spire
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: infrastructure
  source:
    repoURL: 'git@github.com:eitco/argo-hub.git'
    path: clusters/management-cluster/apps/components/spire-components
    targetRevision: 0.1.5
  destination:
    name: in-cluster
    namespace: spire
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true