name: Hello World Workflow

on:
  issues:
    types: [opened]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run when labeled with 'New_Cluster'
      if: contains(github.event.issue.labels.*.name, 'New_Cluster')
      run: |
        echo "Hello World!"

        # Get the issue title
        ISSUE_TITLE=$(echo "${{ github.event.issue.title }}" | tr -d '[:space:]')
        
        # Create a new branch with the issue title
        git checkout -b $ISSUE_TITLE
        
        # Create a file named 'Foobar'
        echo "Content of Foobar file" > Foobar
        
        # Add and commit the changes
        git add .
        git commit -m "Add Foobar file"
        
        # Push the changes to the new branch
        git push origin $ISSUE_TITLE
        
        # Create a pull request
        hub pull-request -m "Add Foobar file" -b main -h $ISSUE_TITLE
